name: ex1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.0-210.1.beta

dependencies:
  # Game engine dependency for RPG mechanics
  flame: ^1.36.0
  bonfire: ^3.16.1
  
  # State management & Communication
  bonfire_bloc: ^0.0.2
  flame_signals: ^0.0.3

  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended lints for Flutter apps
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
